### ISSUE TITLE
Wiktionary translations not visible

### ISSUE THREAD

**Issue by legoscia** [itkach/aard2-android#102]
When I look up a word in Wiktionary using Aard 2, the Translations section is empty - see screenshot below. I can open the same page in a web browser, and then the translations table is visible as a collapsed table that can be expanded.

I am running Aard 2 version 0.43, using the data file `enwiktionary_2018-04-14.slob`.

![Screenshot_20191024-142411_Aard 2](https://user-images.githubusercontent.com/82455/67490366-0528bc00-f66b-11e9-97a1-2aa07a157c43.jpg)

**Comment by itkach** [comment]
I believe this was fixed in a newer dictionary file, there's enwiktionary-20190626.slob at https://github.com/itkach/slob/wiki/Dictionaries#id9, why don't you give it a try?

**Comment by legoscia** [comment]
@itkach That fixed the problem. Thanks!
