### ISSUE TITLE
Support "contains / substring" search

### ISSUE THREAD

**Issue by ilius** [itkach/aard2-android#112]
I'm the author of [PyGlossary](https://github.com/ilius/pyglossary) that's using [slob](https://github.com/itkach/slob) library to create slob files.

Looks like both web and Android apps only search with "startsWith" or prefix query.
I can't find a way to enable substring string (contains query).

Is this something that can be fixed in the slob glossary?

Not sure if it's related, but the [fragment](https://github.com/itkach/slob/blob/master/slob.py#L926) is empty in my [conversion code](https://github.com/ilius/pyglossary/blob/master/pyglossary/plugins/aard2_slob.py#L198).
I tried passing the second word of the key, but results still not showing up when I search the second word.

**Comment by itkach** [comment]
> Looks like both web and Android apps only search with "startsWith" or prefix query.

Yes.

> I can't find a way to enable substring string (contains query).

The only way to achieve this is to build a dictionary with all the substrings for each word added to the lookup index, but then lookup results would be too noisy and unintutive to be useful

> Not sure if it's related, but the [fragment](https://github.com/itkach/slob/blob/master/slob.py#L926) is empty in my [conversion code](https://github.com/ilius/pyglossary/blob/master/pyglossary/plugins/aard2_slob.py#L198).

This is not related. "Fragment" has the same meaning as in URLs - it identifies a location within content

**Comment by ilius** [comment]
Thanks for responding.

**Comment by sobaee** [comment]
I think searching with the 2nd word can be managed with aard2 app itself not with slob glossary.
No need to make a slob file with substrings contained inside of it, just modify the lookup way of aard2 app to lookup in the 2nd word, not just the first word.

**Comment by sobaee** [comment]
This characteristic is called fuzzy search
Many apps supports it
It searches in all keywords with any word you type in search box

**Comment by ildar** [comment]
+1 for fuzzy search. BTW I already requested it:
https://github.com/itkach/aard2-android/issues/25
