### ISSUE TITLE
Unknown file format for Wiktionary

### ISSUE THREAD

**Issue by V3YNjKbFGLSQ0FzpOu1s** [itkach/aard2-android#114]
![Screenshot_20201024-095818_Aard_2](https://user-images.githubusercontent.com/69808482/97070437-df692680-15e0-11eb-821a-1c40b26b47bb.png)

(wordnet-3.1.slob and gcide-0.51.slob works fine)

**Comment by MHBraun** [comment]
Check shsum and redownload enwiktionary.It looks like the file is corrupt.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 10/24/20, 02:09 V3YNjKbFGLSQ0FzpOu1s <notifications@github.com> wrote:

   
   
  (wordnet-3.1.slob and gcide-0.51.slob works fine)

**Comment by MHBraun** [comment]
Can replicate the error.Sha1 error on local source.I will need to update the files.Sorry for the inconveniance.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 10/24/20, 07:45 MHBraun <notifications@github.com> wrote:

   
   
   
   
   
   Check shsum and redownload enwiktionary.It looks like the file is corrupt.--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 10/24/20, 02:09 V3YNjKbFGLSQ0FzpOu1s <notifications@github.com> wrote:
   
   
   
   (wordnet-3.1.slob and gcide-0.51.slob works fine)

**Comment by MHBraun** [comment]
> ![Screenshot_20201024-095818_Aard_2](https://user-images.githubusercontent.com/69808482/97070437-df692680-15e0-11eb-821a-1c40b26b47bb.png)
> 
> (wordnet-3.1.slob and gcide-0.51.slob works fine)

Please close the issue as
- it is not related to the software
- this is not the correct place for it
- the correct place for discussions not related to the software would be https://groups.google.com/g/aarddict
Thank you
