### ISSUE TITLE
Scrolling on grids goes to prev/next article or stops

### ISSUE THREAD

**Issue by CubeGame** [itkach/aard2-android#118]
When trying to scroll on grids, it will try to go to the previous/next article (or stop scrolling when there isn't an article).
Tested on the [periodic table](https://en.wikipedia.org/wiki/Periodic_table#Overview) article.

**Comment by MHBraun** [comment]
Interesting.I can not scroll the Periodic Tabpe anymore. Looks rather like a picture missing the left part.I recall I could scroll the periodic table earlier .--Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 11/12/20, 12:07 Cube <notifications@github.com> wrote:

   
  When trying to scroll on grids, it will try to go to the previous/next article (or stop scrolling when there isn't an article). I had this issue while scrolling on the periodic table.
