### ISSUE TITLE
Changing font and link color in night mode

### ISSUE THREAD

**Issue by shockergit** [itkach/aard2-android#121]
Can you give an option to change font color in night mode. By using the current color its pretty hard to read. Also an option to changing font size would have been good

**Comment by itkach** [comment]
Styles are baked into dictionary. Users can use their own custom styles instead (add CSS file in Settings > User Styles, then in article view go to menu, `Styles...`, select your style)

> Also an option to changing font size would have been good

article view menu, `Zoom In`/`Zoom Out`/`Zoom Reset`

**Comment by shockergit** [comment]
Can you share the css codes for changing font color and background 
It doesn't work
body
{
  background: black;
  font-color: white;
}  
Can you correct this code if there is anything wrong
