### ISSUE TITLE
Convert Freedict Spanish-English dictionary to slob

### ISSUE THREAD

**Issue by meximan** [itkach/aard2-android#125]
https://download.freedict.org/dictionaries/spa-eng/0.3.1/freedict-spa-eng-0.3.1.dictd.tar.xz

Please convert this dictionary to slob and link it to me. Thank you!

**Comment by Yquas** [comment]
Why should anyone do this for you?
Look no further than here: https://download.freedict.org/dictionaries/eng-spa/0.3.1/freedict-eng-spa-0.3.1.slob
And here are all the dictionaries as slob: https://freedict.org/downloads/#smartphones-and-tablets

**Comment by itkach** [comment]
@Yquas thanks for the links, looks like that's what @meximan is looking for. @meximan please use http://aarddict.org/forum/ for dictionary related discussions
