### ISSUE TITLE
[Improvement] Add full description to F-Droid

### ISSUE THREAD

**Issue by Aga-C** [itkach/aard2-android#126]
Hi,

It would be good to add the same app description as there is in Google Play to F-Droid. The one in Play Store describes the app very nicely, but the one on F-Droid is too short and doesn't show the possibilities of the app. Could you give the same description to F-Droid?

BTW. Would it be possible for you to add those descriptions to the repository, so it would be possible to translate them to other languages?

Thanks!

**Comment by itkach** [comment]
I am not publishing to F-Droid and have no access to description there. 

> Would it be possible for you to add those descriptions to the repository, so it would be possible to translate them to other languages?

App description in Google Play is basically a shorter version of README in the repo, so I am not sure what's there to add.

**Comment by UnderSampled** [comment]
F-Droid automatically imports descriptions and screenshots from a repository if it's in the structure [fastlane](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots) uses: [](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure).

I learned about Aard from F-Droid even before Aard2, and use it regularly from there. You can see it's current description [here](https://f-droid.org/en/packages/itkach.aard2/). I appreciate its continued maintenance greatly.

**Comment by Aga-C** [comment]
@itkach I know that description on F-Droid is basically the shorter version of the Readme, but the one on Google Play provides a better description of what the app does, so it makes a better advertisement for it (I myself got interested in Aard2 thanks to it, but prefer downloading from F-Droid). 
If it would be possible to add a description to the repo as @UnderSampled described, it would be really nice.
