### ISSUE TITLE
Cannot navigate path /storage/emulated/0

### ISSUE THREAD

**Issue by JJRcop** [itkach/aard2-android#128]
I tried to manually add a dictionary located directly on my device. The path for this is `/storage/emulated/0`.

When using the plus sign on the dictionaries menu, attempting to navigate to `/storage/emulated` does not display any directories, so I am unable to navigate past this point to `/storage/emulated/0`.

I believe this is how android access permissions are set up. Attempting to list the contents of `/storage/emulated` is denied, but trying to access `/storage/emulated/0` directly is permitted.

It would be nice to allow the app to use my phone's file location menu that other apps take advantage of, which has shortcuts to Internal Storage, and even SD Card.

**Comment by itkach** [comment]
Dictionary selection [0.49](https://github.com/itkach/aard2-android/releases/tag/0.49) now uses native document chooser.

**Comment by francwalter** [comment]
![Screenshot_20220108-211430.png](https://user-images.githubusercontent.com/927269/148658666-0400ccd7-559d-4278-b87b-e2b66ea072b6.png)

None of my dictionaries work anymore now.

**Comment by itkach** [comment]
Yes, you have to remove and re-add them. Old file paths can't work anymore.

**Comment by JJRcop** [comment]
> As far as I can tell, those provide access to actual _file_, not file locations, as in "you can open input stream and read it, but you can't know where the file is and open it yourself". This is not good enough because working with dictionaries requires random access which [content resolver api](https://developer.android.com/reference/android/content/ContentResolver) does not provide (on purpose, so it seems)

Have you resolved this concern with the solution implemented in 0.49?

**Comment by itkach** [comment]
Yes. Turns out with [SAF](https://developer.android.com/guide/topics/providers/document-provider) it's possible to get access via [FileChannel](https://developer.android.com/reference/java/nio/channels/FileChannel) which provides api similar to [RandomAccessFile](https://developer.android.com/reference/java/io/RandomAccessFile?hl=en) that was used before.
