### ISSUE TITLE
Featrure req: Add setting to turn off auto clipboard

### ISSUE THREAD

**Issue by StickyDigit** [itkach/aard2-android#132]
Loving it... however, Aard2 (0.47 from F-Droid) automatically dumps the clipboard into the search term when opened, which may be undesirable if clipboard contains sensitive data e.g. password, or a whole paragraph of stuff.

I often copy chunks of code, whole texts, or other large blobs around, and don't often clear the clipboard. When I open Aard2,  I almost always have to select all and delete to clear the search field before I even begin.

Please add an option to change/stop this behaviour. Perhaps even have it set to off by default, as the behaviour is not normal, expected, or as far as I can see documented.

Maybe add a button for paste if the auto-paste is off and you feel users need a faster way than the usual press-hold-select_paste. IMHO this would be overkill, as I'm happy to use the common built-in paste method across the  board.

**Comment by korhoj** [comment]
I second having a feature for turning the auto paste off.

I'm also loving the app in general :)

**Comment by itkach** [comment]
>  Aard2 (0.47 from F-Droid) automatically dumps the clipboard into the search term

**Comment by itkach** [comment]
> Aard2 (0.47 from F-Droid) automatically dumps the clipboard into the search term

this has been a feature for 6+ years now, added in 0a09610d5c2063fd4e705327cb89baaf44bd82f6 :)

some relevant posts:
https://groups.google.com/g/aarddict/c/2IfkmEWlcRA/m/TXH5QcPeaTIJ
https://groups.google.com/g/aarddict/c/Lg71NHJwbLc/m/PmC70YoftoAJ
https://groups.google.com/g/aarddict/c/ihdORHm0MH4/m/IebuuB9lJRIJ

perhaps an off switch is useful after all

**Comment by StickyDigit** [comment]
Thanks for the links. I'd only checked Github issues. Interesting.

So it won't paste obvious URLs etc. Good. 

Maybe narrow it to only accepting a single all alpha word (maybe allow hyphens, and whitespace/newline either end for sloppy copies)? That would reduce obvious oddness, like dumping whole sentences or lines of code clearly not meant for lookup, and also should screen out all but the worst of passwords.

For me though, a simple off button in settings would be most welcome to make this (unusual) feature an option.

I'd venture a guess that most folk would want it set to "like most other apps" (off) by default.

-- 
Sent from a phone. Please excuse my brevity.

**Comment by itkach** [comment]
Implemented in [0.49](https://github.com/itkach/aard2-android/releases/tag/0.49)
