### ISSUE TITLE
error "no content provider" for wikipedia.slob

### ISSUE THREAD

**Issue by jotwewe** [itkach/aard2-android#135]
For years I have been using aard2 to read two files called "dewiki-20180122-vol-01.slob" and ..02.slob. This works with f-droid versions up to 0.49.
Using 0.50 and 0.51 results in aard2 displaying "no content provider" for those files and not being able to show their contents.

**Comment by francwalter** [comment]
I think you have to delete the slob files in Aard2 and re-search them (with document provider).

**Comment by jotwewe** [comment]
Thank you. Even just upgrading from (the freshly installed) 0.49 to 0.51 just worked.

**Comment by francwalter** [comment]
By the way: warum dont you update the slob files to actual versions from [Halifax](http://ftp.halifax.rwth-aachen.de/aarddict/dewiki/dewiki20220126-vol/)?
There is always very actual dewiki from good mhbrown there :)
