### ISSUE TITLE
[Feature request] please support vertical scrolling

### ISSUE THREAD

**Issue by sobaee** [itkach/aard2-android#137]
First thanks for your great app.

I just like aard2 app and I need to use it as my one and only multidictionary viewer app.

Could you please add the ability to vertically scroll the results, not just horizontal scrolling, because it's more suitable for some people.

is it possible to have a style css file which makes you able to vertically scroll the results? 

Thanks a lot

**Comment by itkach** [comment]
When an article is scrolled to the bottom, "volume down" button moves to the next result, "volume up" at the top moves to previous result (or back to lookup, if on first result). Up/down volume button long press jumps to top/bottom. Are you looking for something like this or do you have something else in mind?

**Comment by sobaee** [comment]
Not that feature.
 I meant to be like other multi dictionary viewers, that you could see the results of each dictionary below each other in one long page, not beside each other

See this example:

![Screenshot_20220225154515](https://user-images.githubusercontent.com/65910585/155717327-cab14a48-7cff-468b-861e-ad642f7ee302.jpg)

So, each dictionary will be below the other

**Comment by itkach** [comment]
I see. This has been discussed before, see #79
