### ISSUE TITLE
bug, doesn't see dictionaries

### ISSUE THREAD

**Issue by OmlineEditor** [itkach/aard2-android#138]
after the update, the program does not work, does not see dictionaries. Dictionaries have not changed, they are lying in place.

Aard 2 v0.51 (51) f-droid
Android 9.0

[log_bug.txt](https://github.com/itkach/aard2-android/files/8207493/log_bug.txt)

**Comment by itkach** [comment]
You need to re-open dictionaries after update to version > 0.48.
