### ISSUE TITLE
Symbols in search text are ignored

### ISSUE THREAD

**Issue by sjl872964789** [itkach/aard2-android#140]
**Describe the bug**
Symbols in search text are ignored

**To Reproduce**
1. Open the app
2. Favorite any word that contains a symbol (eg . - ' ~)
3. Click on the Favorites list
4. Search for the word
5. Many words that do not contain this character will also be searched

**Expected behavior**
When searching should also search for symbols

**Screenshots**
https://user-images.githubusercontent.com/15941953/161544689-ae102143-d609-4713-83c0-0c67e8f63e74.mp4

**Smartphone (please complete the following information):**
- OS: Hydrogen OS
- Rooted: No
- Version: 0.51
- Device: OnePlus 8T

**Comment by itkach** [comment]
This mode of matching - ignoring punctuation-like symbols - makes some searches easier, for example something like `L'Ardève` can be found by typing just `la`. But it does put titles containing punctuation at a disadvantage and is overall somewhat unintuitive. I'll change it.

**Comment by ildar** [comment]
Does this mean that search becomes strict to umlauts and diacritics ? If so
can this be optional? Thanks

**Comment by itkach** [comment]
It does not. This is about filtering bookmarks/history and only changes
treatment of punctuation-like symbols.
