### ISSUE TITLE
App crashes when the device's Bluetooth is not turned on

### ISSUE THREAD

**Issue by androidAppGuard** [itkach/aard2-android#141]
App version: 0.40
Android version: 6.0
Device: Nexus 5
Step to reproduce:
   1. Import a dictionary
   2. click a random word
The stack trace is:
04-23 22:04:26.730  2491  2813 I MdiSyncModule: initializing module...
04-23 22:04:26.797  2086  2458 W Nearby  : Failed attempt #3 out of 3 for RestoreDeviceName [CONTEXT service_id=49 ]
04-23 22:04:26.797  2086  2458 W Nearby  : java.lang.IllegalStateException: BluetoothAdapter not ready yet!
04-23 22:04:26.797  2086  2458 W Nearby  : 	at ajpy.d(:com.google.android.gms@202414023@20.24.14 (040800-319035315):2)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at ajpx.run(Unknown Source)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at bwuj.call(Unknown Source)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at bwuo.a(:com.google.android.gms@202414023@20.24.14 (040800-319035315):2)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at bwuo.a(:com.google.android.gms@202414023@20.24.14 (040800-319035315):9)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at ajpw.run(Unknown Source)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at java.lang.Thread.run(Thread.java:818)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at sow.run(Unknown Source)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at sux.run(:com.google.android.gms@202414023@20.24.14 (040800-319035315):0)
04-23 22:04:26.797  2086  2458 W Nearby  : 	at java.lang.Thread.run(Thread.java:818)

**Comment by itkach** [comment]
- Stack trace doesn't come from aard2 app
- I can't reproduce
- Current app version is 0.53, 0.40 is ancient.
