### ISSUE TITLE
[Bug?] F-Droid version 0.52 & 0.53 (latest as of now) are of wrong file size! (too big)

### ISSUE THREAD

**Issue by NA0341** [itkach/aard2-android#142]
They're both 11MB big while versions on GitHub changed only by a few kilobytes with versions (0.53 being 3.38MB).
![Screenshot_20220507-104447](https://user-images.githubusercontent.com/26059513/167247000-2a80713a-4035-4375-bbaa-3471795eb0aa.png)

**Comment by MHBraun** [comment]
Why do you not download the file from the source?

https://github.com/itkach/aard2-android/releases

I would not trust an app with modified size. Who knows what it will do....



________________________________
From: NA0341 ***@***.***>
Sent: Saturday, May 7, 2022 02:53
To: itkach/aard2-android
Cc: Subscribed
Subject: [itkach/aard2-android] [Bug?] F-Droid version 0.52 & 0.53 (latest as of now) are of wrong file size! (too big) (Issue #142)

They're both 11MB big while versions on GitHub changed only by a few kilobytes with versions (0.53 being 3.38MB).

**Comment by itkach** [comment]
Address your question to F-droid. They rebuild from source. I don't know how do they build it, perhaps they do not exclude unused ICU data files listed in exclude.txt
