### ISSUE TITLE
app is crashing

### ISSUE THREAD

**Issue by OmlineEditor** [itkach/aard2-android#145]
when opening words in the dictionary, the application crashes.

My Androin 9.0
AARD from Fdroid v0.53

[log_aard2.txt](https://github.com/itkach/aard2-android/files/8827775/log_aard2.txt)

**Comment by itkach** [comment]
That's a strange bunch of errors. Looks like system WebView is messed up somehow. Does it crash the same way if installed from  https://github.com/itkach/aard2-android/releases/tag/0.53 ?

**Comment by OmlineEditor** [comment]
If this is a WebView error then you just need to say it without crashing. to solve the problem, I just deleted the application and installed it again. but it's very strange, it shouldn't be like this. Please report bugs without crashing the app

**Comment by itkach** [comment]
Glad to hear you were able to resolve the issue. As for not crashing - there's nothing the application can do if embedded system component crashes.

**Comment by OmlineEditor** [comment]
can't you just say that webview is broken? why does the app crash?
can you make an alert without crashing the app?
