### ISSUE TITLE
Aard 2 crashed at splashscreen when network permission disabled

### ISSUE THREAD

**Issue by DougInAMug** [itkach/aard2-android#149]
As in title: app opens fine with network permission enabled, but when it's disabled, it refuses to start at all. I would like to be able to use the dictionary without network permissions.

Aard2 version: 0.53
Android: 13

Happy to provide any more details, but I'm not an Android dev, so please instruct me how to obtain logs if required!

**Comment by itkach** [comment]
The app uses embedded web server (
listening on localhost only), AFAIK that still requires network permission even if it's local.

**Comment by yumeo-ch** [comment]
I second this request, would be nice to find a way to use without network access.
