### ISSUE TITLE
unable to reorder dictionaries

### ISSUE THREAD

**Issue by rhjdvsgsgks** [itkach/aard2-android#157]
before the version using saf. i can change the order of dictionaries by adding them sequentially. but, after update to recent version. i cant do that anymore. dict always list in a fixed order. no matter when i add it.
could you please add a reorder feature. so that i can control which dict will be shown first when jumping from text action

**Comment by itkach** [comment]
you can order dictionaries (sort of) by marking them as favorite (star), starred dictionaries are first in the list
