### ISSUE TITLE
Link coordinates to geo: intent

### ISSUE THREAD

**Issue by shorty66** [itkach/aard2-android#16]
GPS Coordinates are used in many Wikipedia articles.
These coordinates usually link to https://tools.wmflabs.org/geohack... which is a website which gives links to all sorts of geo-services.
On a smartphone, it would be more apropriate to use the geo: intent instead, as this would allow to directly view the coordinates with an Android app.
This is especially useful when no interent connection is present: It would not be possible to acces wmflabs.org/geohack while an offline map APP like OSMAnd could display the map.

There are several ways to solve this: 
1. When compiling the .slob file, https://tools.wmflabs.org/geohack.. liks could automatically be converted.
2. Conversion could be done by the Android App whenever a link to https://tools.wmflabs.org/geohack is found.
3. Conversion could be done by the Android App whenever a link containing coordinates in the form of ...40.712777777778_N_74.005833333333_W... is found

I think 1. is the best option to reduce complexity of the Android App.

**Comment by MHBraun** [comment]
Correct.
However if the user is online he has no access to other services with solution 1.
With solution 2 in case of no internet an internal connection could be established. In case of Inet connection the link could be followed. This would probably require a user setting how the app should behave. Use internet connection or not in case it is available.
But you are right, this would increase App complexity.

**Comment by itkach** [comment]
Fixed in https://github.com/itkach/mwscrape2slob/commit/f8240e51d70a494559f7f1b591cb048818e2897b

**Comment by ce-4** [comment]
Has this feature been removed or become a regression? I cannot find the button anymore but remember that it was present some (maybe long) time ago.

My use case is: offline use of Aard2 when eg. traveling a foreign big city and reading the relevant places' wikipedia which often have geo coordinate references. I'd like to be able to quickly open the place in native map apps like Osmand. Currently i have to copy the tools.wmfla.org link, extract the and paste the coordinates into the map app's search.

**Comment by itkach** [comment]
> Has this feature been removed or become a regression?

The link is created when creating/compiling dictionary, it's article content rather than a feature of aard2-android app itself. Maybe Mediawiki changed how geo coordinates are rendered and @itkach/mwscrape2slob [ code to find it ](https://github.com/itkach/mwscrape2slob/blob/f8240e51d70a494559f7f1b591cb048818e2897b/mwscrape2slob/__init__.py#L405)no longer works.
