### ISSUE TITLE
Pocketbook e-ink

### ISSUE THREAD

**Issue by x3oo** [itkach/aard2-android#160]
Is it possible to make this run on pocketbook devices?

https://github.com/koreader/koreader
is an example for an app that runs on pocketbook

**Comment by itkach** [comment]
This application is designed to run on Android OS. My understanding is that Pocketbook devices run a Linux-based OS, not Android, so the answer is no, it is not possible.

**Comment by x3oo** [comment]
Pocketbook runs on Android too

itkach ***@***.***> schrieb am Mi., 28. Juni 2023, 15:51:

**Comment by itkach** [comment]
> Pocketbook runs on Android too

In that case the app should work there, at least in theory. Android customization done by the device manufacturer may affect compatibility though, so the only way to  find out is to actually try it :)

**Comment by x3oo** [comment]
You can't use APK. Koreader has published their tool chain but I don't know
enough.

itkach ***@***.***> schrieb am Mi., 28. Juni 2023, 17:16:

**Comment by itkach** [comment]
> You can't use APK.

That would be very strange if it is indeed Android. APK sideloading is probably disabled by default and typically needs to be explicitly enabled in device settings, although manufacturer may have chosen to not expose that functionality.

I am curious though which Pocketbook models are you talking about. I could only find mentions of Android-based Pocketbook [here](https://www.mobileread.com/forums/showthread.php?t=353745), and this model is not released yet.

**Comment by x3oo** [comment]
i think you are right, its probably not android. 
but having aard on an ebookreader would be the real world implementation of having a the hitchhikers guide to the galaxy.
