### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by ahstro** [itkach/aard2-android#162]
Using Aard2 offline (airplane mode and no wifi) doesn't seem to work reliably for me. After connecting to wifi it works, and after disconnecting it works for a while, but eventually it just stops loading pages/definitions and throws this error:

![Screenshot_20230801-174100_Aard 2_1](https://github.com/itkach/aard2-android/assets/3090888/89622fbe-6dcd-4aa9-a42b-efa064583a47)

I've tried with multiple different dictionaries, clearing cache and storage, un-/reinstalling the app, and even using Termux and `su` to find all aard2 related files on the system and deleting them.

**Comment by itkach** [comment]
I am unable to reproduce this, works fine on Samsung Android 12. Can you tell more about your system? Which Android version does it run? It looks like some kind of power saving mode is on, shouldn't matter but I'm curious if turning that off makes a difference. Also, are you by any chance running any software on your phone that may be messing with networking, like DNS-based ad blocker or something like that?

**Comment by ahstro** [comment]
I'm running LineageOS 19, based on Android 12. I am usually using AFWall+ and AdAway, but tried disabling both and it still didn't work. I believe I tried disabling battery saver as well, but I am not sure. I can do some more testing soon. The OS does have a battery usage mode per app, which can be "Unrestricted", "Optimized", or "Restricted", and it is currenlty set to "Optimized", so that might be part of the equation. I have seen other apps mention turning that off for things to work properly, so maybe that would be a potential solution if that turns out to be the problem.

**Comment by ildar** [comment]
would be nice to see `netstat -anp` and `ps -ef | grep aard` in the root
shell. If only you understand what I'm writing about.

**Comment by ildar** [comment]
BTW stopping the AFWall app doesn't mean the firewall is disabled. @ahstro
please doublecheck.
