### ISSUE TITLE
Dark theme for articles is missing in Aard2 0.54

### ISSUE THREAD

**Issue by alex-rusakevich** [itkach/aard2-android#163]
Xiaomi Redmi 10, MIUI 13 (Android 12)

All the articles remain white with any of these themes.

If this cannot be fixed yet, could you, @itkach , share article's theme file for us to write our own themes, please?

![Image 1](https://github.com/itkach/aard2-android/assets/25137472/1213d503-12e7-43e2-8ad5-2a847fcbb3fe)

**Comment by itkach** [comment]
Alternate styles are part of the dictionary, looks like this one does not include any. See for example https://github.com/itkach/xdxf2slob/ on how to do it. Note [alternate stylesheet link](https://github.com/itkach/xdxf2slob/blob/master/xdxf2slob/__init__.py#L35C1-L35C1),  [css directory being added to the dictionary](https://github.com/itkach/xdxf2slob/blob/master/xdxf2slob/__init__.py#L318) and [css file itself](https://github.com/itkach/xdxf2slob/blob/master/xdxf2slob/css/night.css)

**Comment by alex-rusakevich** [comment]
Thank you for the reply, @itkach ! 
I've started a project with themes for aard2 based on your answer, if you don't mind. It is located [https://github.com/alex-rusakevich/aard2-themes/tree/master](here).
