### ISSUE TITLE
Search field should have focus

### ISSUE THREAD

**Issue by valentina-ka** [itkach/aard2-android#165]
Hello,

First of all, thank you for the hard work on Aard 2.

I noticed, however, a behavior of Aard 2 that is making me lose time pretty regularly: You can’t directly start typing a word. In other words, the search field doesn’t have focus, neither when you launch the app, nor when go back to the LOOKUP screen after being on another Aard 2 screen.

What’s even more frustrating is the search field has a relatively compact height, and immediately under it, there are 5 buttons that are easy to misclick, 4 of which (BOOKMARKS, HISTORY, DICTIONARY MANAGEMENT, etc.) will **hide** the search bar. Maybe I have clumsy fingers, but I swear that 30% of the time when I am clicking the search field, desperately trying to make it get focus (which it should have on its own!!!), the search field goes away inadvertently.

**Comment by itkach** [comment]
I am unable to reproduce this on a Samsung Galaxy with One UI 4.1/Android 12. Lookup input field is automatically focused and keyboard pops up in all cases you describe, as well as when clearing previous input using x button. The height of the input field appears to be consistent with input fields in other applications.

**Comment by francwalter** [comment]
I cannot reproduce it neither. I open Aard2, the search input is already filled with my last search, so not empty, and the keyboard opens and the focus is in the search input.
So even when not empty it has the focus.
What phone do you use?
It could be OS (manufacturer) related.

But I have to say that I use the fork of Aard2 with the buttons at the bottom. I don't know if there is different behavior in this matter. 
frank

**Comment by MHBraun** [comment]
Can confirm this behavior on Samsung A52s 5G (SM-A528B/DS) running OneUI 5.1 on Android 13.

 

The keyboard does not open if the app is not in the background before and there is an existing entry in the search field. If the search field is empty, the keyboard opens immediately. 

 

I have miracle fingers with phones and computers, so I can not replicate the 5 button issue. ;)

 

 

From: valentina-ka ***@***.*** 
Sent: Freitag, 1. September 2023 22:11
To: itkach/aard2-android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [itkach/aard2-android] Search field should have focus (Issue #165)

 

Hello,

First of all, thank you for the hard work on Aard 2.

I noticed, however, a behavior of Aard 2 that is making me lose time pretty regularly: You can’t directly start typing a word. In other words, the search field doesn’t have focus, neither when you launch the app, nor when go back to the LOOKUP screen after being on another Aard 2 screen.

What’s even more frustrating is the search field has a relatively compact height, and immediately under it, there are 5 buttons that are easy to misclick, 4 of which (BOOKMARKS, HISTORY, DICTIONARY MANAGEMENT, etc.) will hide the search bar. Maybe I have clumsy fingers, but I swear that 30% of the time when I am clicking the search field, desperately trying to make it get focus (which it should have on its own!!!), the search field goes away inadvertently.
