### ISSUE TITLE
Unable to load content in Android 12

### ISSUE THREAD

**Issue by drpo** [itkach/aard2-android#167]
test apk from F-Droid and GitHub Release, 0.53 and 0.54

test command: `curl -v 127.0.0.1:8013`
on Android 11, response with *404 Not Found*
on Android 12, got *Connection timed out*

**Comment by itkach** [comment]
on Android 12, do you run any software that modifies networking, such as ad blockers or vpn?

**Comment by drpo** [comment]
not the issue of app
