### ISSUE TITLE
[Feature Request] Allow regex in search

### ISSUE THREAD

**Issue by knkski** [itkach/aard2-android#169]
Thanks for the great app! I'm wondering if it would make sense to allow for using a regex to search. Sometimes, I'd like to find all words that match a patterns such as `a.*b.*c`, and as far as I can tell that functionality doesn't exist. Does it make sense to add that in? I might be able to open a PR myself too if that would be preferred.

**Comment by itkach** [comment]
> make sense to allow for using a regex to search

the way lookup works it's not possible to use regex
