### ISSUE TITLE
Random Search

### ISSUE THREAD

**Issue by GiftedPowerfulWinner** [itkach/aard2-android#18]
Здравствуйте.
Скажите пожалуйста, возможно ли/планируется ли расширение функционала ''случайного поиска'' (кнопка в левом верхнем углу), чтобы он мог искать только в рамках какого-либо одного словаря, даже если подключённых к программе несколько.
Не по всем вразнобой, а случайные результаты по какому-либо одному, а сам словарь на выбор пользователя. 
Ну и текущий вариант (по всем), чтобы оставался опционально возможным.

**Comment by sklart** [comment]
Да, Игорь, я на форуме собственно просьбу *GiftedPowerfulWinner* перед этим и озвучил.

**Comment by GiftedPowerfulWinner** [comment]
itkach
Лично меня, да, устроит вариант, что 'выключенные' словари исключатся из случайного поиска. Это будет логично, и сообразно настройкам) Авансом - спасибо, за появление этой фичи в новых версиях.

Насчёт возможной перегруженности интерфейса при иных вариантах - понимаю, о чём вы говорите.
Опишу одну альтернативу, на всякий, вдруг пригодится.
Если кто-то пользовался андроидной или pc версией программы foradict, то в курсе как это выглядит. На главном экране нажимается кнопка random и появляется всплывающее окно со списком всех подключёных словарей, каждый из которых в данном случае кликабелен. Ну и нажимая на конкретный ''рандомный поиск'' направляется строго на него.
Плюсы - все словари всегда доступны для случайного поиска, без отключений.
Вобщем, такая альтернатива, насколько это целессообразно/сложно/нужно было бы реализовать - на усмотрение itkach.

sklart
Да, спасибо, был не в курсе, что вы мою просьбу уже телепортировали) Как впрочем и не знал сначала, что автор говорит на русском, и можно напрямую пообщаться.

**Comment by itkach** [comment]
> всплывающее окно
> нажав на конкретный словарь

Выскакивающие окна и выбирать каждый раз конечно никуда не годится. Могу добавить опцию искать только в "любимых" словарях.

**Comment by GiftedPowerfulWinner** [comment]
Могу добавить опцию искать только в "любимых" словарях.

Было бы круто, когда только появились ''звёздочки'', я подумал они для этого и нужны)
На этом с моим фидбэком всё наверное, на данный момент.
Мерси за отклик, буду ждать новые ревизии.

**Comment by itkach** [comment]
> я подумал они для этого и нужны

Звёздочки нужны в основном, чтобы менять порядок словарей (перетаскивать выглядит конечно круче, но стандартного виджета нет и таскать на большие расстояния не так уж и удобно). Менять порядок словарей бывает полезно, так как результаты одинаковой "релевантности" показываются в том порядке, в каком словари, особенно важно при поиске из других программ когда сразу открывается статья. Возможно когда-нибудь будет опция, чтобы порядок  словарей имел приоритет над релевантностью.

**Comment by itkach** [comment]
Fixed in acebd5b4f01932dcb993e8f1ebad2bf36e4ccf60 and 3187facdc27deed9feb066a3c2e106bf9fcb8167
