### ISSUE TITLE
 The layout is inconsistent using the "Zoom Out" setting

### ISSUE THREAD

**Issue by liushuqi-2022** [itkach/aard2-android#180]
**To Reproduce**
1.Go to the word details page
2.Click ”More Options“
3. Click "Zoom Out"

**Expected behavior**
The layout of word details is not disordered

**Record**
[untitled.webm](https://github.com/itkach/aard2-android/assets/111285450/99961e20-2c79-4550-99a1-dcf7c01620f2)

**Environment**
Android version: 8.0
Device: pixel XL
App Version: 0.56

**Comment by itkach** [comment]
For layout-preserving zoom, use pinch gesture. Zoom In/Out actions are text zoom - increase/decrease text size. This is the behavior of Android's WebView component, not something the app can change.

**Comment by liushuqi-2022** [comment]
> For layout-preserving zoom, use pinch gesture. Zoom In/Out actions are text zoom - increase/decrease text size. This is the behavior of Android's WebView component, not something the app can change.

Thank you for your concern about this issue.
