### ISSUE TITLE
updated app to androidx / material and feature improvements

### ISSUE THREAD

**Issue by farfromrefug** [itkach/aard2-android#184]
Just so it is known and to prevent someone starting this. I started working on upgrading the project and improving UX  / features.
The work is happening here https://github.com/farfromrefug/aard2-android
Here are a few screenshots

| | |
|---|---|
|![Screenshot_1718981446](https://github.com/itkach/aard2-android/assets/655344/0d45958a-37c1-46bf-8512-a19c264c16c9)|![Screenshot_1718981451](https://github.com/itkach/aard2-android/assets/655344/81249b94-f787-4c21-aec4-2e6471a077c3)|
|![Screenshot_1718981453](https://github.com/itkach/aard2-android/assets/655344/2a8b81fa-6a4d-4716-a551-fcfa2513aa18)|![Screenshot_1718981460](https://github.com/itkach/aard2-android/assets/655344/81d51ba0-a490-4da9-8e8c-8b27258d52c1)|
|![Screenshot_1718981464](https://github.com/itkach/aard2-android/assets/655344/cc7d5291-913d-4635-ae01-35ab2b5e10c7)|![Screenshot_1718981468](https://github.com/itkach/aard2-android/assets/655344/5034a23e-44d7-4d1d-abef-232cb34f8daf)|

**Comment by soshial** [comment]
If your changes become huge, those won't be merged into the official repo.
Please split them into branches, make pull requests and only then it's possible to review and merge.
Also, depends on whether @itkach has any will to continue this project.

**Comment by farfromrefug** [comment]
@soshial yes i know. But the migration has to be a big one. Androidx/material are really linked.
And yes it depends on @itkach wanting to continue. @itkach if you need help maintaining this i am really interested in helping.

**Comment by soshial** [comment]
BTW, there have been several huge forks with full rework of this app (but I suppose those are stale now) — you may find cool things to rebase on or improve on.

**Comment by farfromrefug** [comment]
@soshial Nice did not know. Will take a look

**Comment by itkach** [comment]
@farfromrefug thank you, I appreciate the effort. So far it looks mergeable. Even though it is technically quite big in terms of number of changes, most of these changes appear to be rather mechanical/cosmetic, nothing changes conceptually.  I do see, however, some changes unrelated to androidx migration already crept in: for example replacing switch statements with ifs [here](https://github.com/itkach/aard2-android/compare/itkach:7c95f15...farfromrefug:a7a46d4#diff-56cea31d6a23da9b97ea26e1fedee403d2a05de51b5d41f35f72c1bf48ec3004L134-R141) and [here](https://github.com/itkach/aard2-android/compare/itkach:7c95f15...farfromrefug:a7a46d4#diff-56cea31d6a23da9b97ea26e1fedee403d2a05de51b5d41f35f72c1bf48ec3004L134-R141) and in other places, or an [attempt at issue fix](https://github.com/itkach/aard2-android/commit/448be3368b7ed803a6fcb6f1fa80bac0b3dcbb5b), or [merging a pull request](https://github.com/itkach/aard2-android/commit/8a4f6317a5ef414b5954bbf91946a6bcc445e51d), or tooling updates. While such changes are not necessarily blockers (and some may even be unavoidable, like tooling updates aggressively forced by Google), they do make it more difficult to review and test, and may make it impossible to merge if enough of them are accumulated in one PR.

> BTW, there have been several huge forks with full rework of this app (but I suppose those are stale now) — you may find cool things to rebase on or improve on.

If that's what you would like to do (full rework) then I think the best course of action would be to keep that as a separate project and release it under a new name. I'd be happy to recommend users check out such a new application when it is ready. 

> depends on whether @itkach has any will to continue this project.

I achieved my personal goals I had with this project a long time ago. I do keep using it myself (lightly) and I would like to keep it in working order for the foreseeable future if I can, but I do not plan or want any new major development. Small fixes and tweaks, occasionally catching up with Android tooling, refreshing the look/theme  - sure. Re-architecting the app, re-thinking navigation patterns and UI in general, re-organizing the code, re-writing in Kotlin (as someone suggested once) - all these may be great ideas potentially resulting in great new app(s) but I think they are best pursued as their own separate projects.

**Comment by farfromrefug** [comment]
@itkach switch migration to if is needed because it is not supported anymore in latest java.
For the other changes indeed ( you did looked at it all ;))  i will move them to a separate PR. I am working on multiple things at the time. Dont worry i will separate all that!

As for the future and big updates like architecture, navigation,..., i am willing (if it is something i need as my personal need for this app) to implement them. If you agree you could add me as to this repo and i could implement such things with PRs so that you can still have a look at it

**Comment by itkach** [comment]
> @itkach switch migration to if is needed because it is not supported anymore in latest java. 

Hm... that would be a pretty incredible breaking change in Java, and indeed I can't find any documentation that would support this statement. Can you elaborate?

**Comment by soshial** [comment]
You can read more about [problems with switch statements here](https://web.archive.org/web/20230205001121/https://sites.google.com/a/android.com/tools/tips/non-constant-fields).

Basically it won't compile if the integer is not final:

<img width="641" alt="Screenshot 2024-06-28 at 18 44 41" src="https://github.com/itkach/aard2-android/assets/100644/7e359378-319d-4dba-9ba8-10381f4e7be8">

**Comment by itkach** [comment]
Ah, so switch is supported in latest Java just fine - phew, got me worried there for a moment! 😌 - this is android tooling issue, thank you for clarifying. Looks like, more specifically, it's a breaking change in [Android Gradle Plugin 8.0.0 defaults](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes). Since this defaults change doesn't benefit this app in any meaningful way, an easy way to avoid changing the switch statements would be to explicitly set `android.nonFinalResIds` to false or even better - gasp! - to not make gradle plugin upgrade part of these changes.

**Comment by soshial** [comment]
I am not sure `android.nonFinalResIds=true` will help against this. Also, I think that upgrading gradle plugin is needed to use the latest Android Studio.

**Comment by itkach** [comment]
> android.nonFinalResIds=true

You mean `android.nonFinalResIds=false`. `true` is the new default, `false` is the previous default. 

> I am not sure ... will help against this. 

Why not?

**Comment by soshial** [comment]
Updated my answer

**Comment by farfromrefug** [comment]
@itkach i think upgrading to gradle 8 is kind of a must have. Anyway at one point you will be force too to be compatible with latest targets and thus release with new features.
As for the change to switch to if, I dont think what the issue is. If it is the default in latest gradle/java I guess it means it is optimized in some way. Otherwise the default would have remain to allow the switch.

But anyway it is your choice, just dont see the issue in migrating to if

**Comment by itkach** [comment]
> As for the change to switch to if, I dont think what the issue is. If it is the default in latest gradle/java I guess it means it is optimized in some way. Otherwise the default would have remain to allow the switch.

It optimizes something that this application doesn't need optimized while forcing unnecessary code changes. This is a misguided default change - which is par for the course for Android. 

Anyway, this conversation started with you saying "switch migration to if is needed ..." and I'm just pointing out that's not the case, that's all.

**Comment by farfromrefug** [comment]
@itkach yes sure dont worry I ll create à PR for what you accept and the rest will remain in my fork. Might just come a point where I cant PR anymore as it does not align with my goals. 
At that point I might create a new app. 
Thanks a lot for everything you Ve done.

I am still "comparing" your slob format and zim.
Your slob are much smaller which interest me. Plus I cant get remote content load to work in zim/kiwix

**Comment by soshial** [comment]
BTW, @farfromrefug, if you maintain this app (or its fork), I'll come in and help from time to time with some features/bugfixes/improvements, because I use this app really often.

**Comment by farfromrefug** [comment]
@soshial thanks a lot. Yes i think i might have to go for a work. I am already making more changes for better usability and i have more ideas.

**Comment by soshial** [comment]
BTW, since you're migrating to Material Theme, @farfromrefug, it would be cool to migrate the tabs as well:
* to show their names under the icon
* put them in them bottom for better UX

![image](https://github.com/itkach/aard2-android/assets/100644/e2936deb-eedd-4d64-aa2c-648213720dec)
![image](https://github.com/itkach/aard2-android/assets/100644/ddf929ff-640c-4e08-bcd4-b6831ea94cd1)
![image](https://github.com/itkach/aard2-android/assets/100644/f810918c-a55c-4870-aa4e-8c3b74ed0178)

**Comment by farfromrefug** [comment]
@soshial Yes i plan on going full material. Just gonna take some time as this mean true rewrite not just theme / style migration

**Comment by soshial** [comment]
Wow, this looks pretty much amazing, @farfromrefug! 🔥
Thanks for removing that weird font file and making the app completely in Kotlin.
So what are your plans for the app? How are you going to name it?

**Comment by farfromrefug** [comment]
@soshial i have no idea :D Materiaard ? :P 
I am also working on making the article loading much faster. Until now it was quite slow because multiple articles were loaded at the same time

**Comment by Benko111** [comment]
That looks good. Is there already a compiled version somewhere?

**Comment by farfromrefug** [comment]
@Benko111 here you go https://github.com/farfromrefug/aard2-android/releases/tag/v1.0.0

**Comment by soshial** [comment]
Good job! And thanks a lot for publishing the app, @farfromrefug!
I found several crashes in your app, but there is no "Issues" tab in your repo: https://github.com/farfromrefug/aard2-android

Could you open it please? Also, please cherry-pick [these fixes](https://github.com/farfromrefug/aard2-android/compare/master...itkach%3Aaard2-android%3Amaster) from the upstream app, @farfromrefug.

**Comment by farfromrefug** [comment]
@soshial you can now create issues

**Comment by soshial** [comment]
Thanks. I think my crash was fixed by [this commit](https://github.com/farfromrefug/aard2-android/commit/3db51b8bf93492b61a4c4ba78fa8cfdf09640a1c). Could you please the same fix in your repo , @farfromrefug? I will test whether it fixed my crash then.

**Comment by farfromrefug** [comment]
@soshial let s move that discussion to my repo if possible. I did merge that fix. need to release it

**Comment by shuvashish76** [comment]
> BTW, there have been several huge forks with full rework of this app (but I suppose those are stale now) — you may find cool things to rebase on or improve on.

e.g. - #154 I'm still using Muntashir version. Please do have a look on their design/changes. ThankYou for showing interest to maintain the fork.
