### ISSUE TITLE
BUG: dictionaries cannot be deleted

### ISSUE THREAD

**Issue by soshial** [itkach/aard2-android#186]
https://github.com/itkach/aard2-android/assets/100644/aff6468d-dc6f-4011-8772-fa9d5957f5b1

**Comment by itkach** [comment]
Interesting. Looks like app state is not persisted or is somehow rolled back when you kill the app. Is it the same if you keep using the app for a bit longer after forgetting the dictionary or does it come back anyway? Anything interesting/unusual about your device or OS? I am unable to reproduce this, works for me on Galaxy S10 with Android 12.

**Comment by soshial** [comment]
I have Samsung Galaxy S22. After forgetting a dictionary I left the app open for a minute and then closed.
This dictionary still reappears.

PS. Another dict is shown twice in the list, but this is probably another bug.

**Comment by itkach** [comment]
I think I know [how this happens](https://github.com/itkach/aard2-android/discussions/187#discussioncomment-9909302)
