### ISSUE TITLE
com.android.externalatorage has no access

### ISSUE THREAD

**Issue by curability4apish** [itkach/aard2-android#190]
![Screenshot_20240927_043325_Aard 2.jpg](https://github.com/user-attachments/assets/f21ac890-0616-418b-84c1-f49346d09e24)

**Comment by itkach** [comment]
Without any other additional information my guess would be that the file is no longer there, perhaps it was deleted or renamed? Remove the dictionary (trash icon) and add it back again.

**Comment by curability4apish** [comment]
I use built-in Android file picker, and the problem doesn't resolve when I retry.

**Comment by itkach** [comment]
Strange.  Some googling turned up [this thread](https://www.reddit.com/r/kustom/comments/18fnha2/kwgt_error_comexternalstorage_has_no_access/) which describes the same issue in a different app, and [this comment offers a solution](https://www.reddit.com/r/kustom/comments/18fnha2/comment/kcwe6g8/). Can you try these instructions and see if it helps?

> Go to settings, apps, in the upper right you'll see 3 dots stacked, press that, then open special access, then all files access, in the upper right of that menu press the 3 dots then press show system apps and look for "external storage" and toggle on the switch to the right to give it permission.

**Comment by curability4apish** [comment]
Thanks but I don't see three dots stacked following the instruction. I don't see the app in settings > access to all files section either.

I am using Galaxy A54 5G, the latest version of OS.

**Comment by itkach** [comment]
<img width="366" alt="image" src="https://github.com/user-attachments/assets/77ace2d6-d76c-4036-8f7e-0ffb707c6a81">

Do screens on your device look different?

**Comment by curability4apish** [comment]
The problem is resolved. Thank you very much.
