### ISSUE TITLE
[question] is there any English-Spanish dictionary?

### ISSUE THREAD

**Issue by throwaway242685** [itkach/aard2-android#192]
I've been looking everywhere but I can't seem to find it.

**Comment by itkach** [comment]
There's [Spanish wiktionary](https://github.com/itkach/slob/wiki/Wiktionary-and-Wikibooks#spanish), eng-spa freedict [here](https://github.com/itkach/slob/wiki/Word-dictionaries-(Wordnet-and-Freedict)#freedict)  or [newer version here](https://freedict.org/downloads/#dictionary-downloads). There are also Spanish language dictionaries in XDXF format at https://sourceforge.net/projects/xdxf/files/ - these can be converted using either [xdxf2slob](https://github.com/itkach/xdxf2slob) or [pyglossary](https://github.com/ilius/pyglossary). [Pyglossary](https://github.com/ilius/pyglossary) can also convert from other formats.
