### ISSUE TITLE
Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider

### ISSUE THREAD

**Issue by et9235** [itkach/aard2-android#194]
Having issues opening dictionaries on SD card.
Aard2 v0.58, installed via F-Droid on a brand new Moto G85 (fully updated) less than 24hr ago.

See attached for below for error.
![image](https://github.com/user-attachments/assets/aa458f6f-c1d0-4a67-af30-8de7a4881422)

**Comment by itkach** [comment]
Try remove and re-add these dictionaries.

**Comment by et9235** [comment]
> Try remove and re-add these dictionaries.

Resolved!
