### ISSUE TITLE
[FR] small screen-friendly zoom

### ISSUE THREAD

**Issue by ildar** [itkach/aard2-android#22]
Aard(1) has a zoom with re-layouting so no horizontal scroll appears. Could you implement this in Aard2? Thanks in advance.
I couldn't find exact name of this feature, could you name it? Just one reference: https://github.com/aarddict/android/issues/93#issuecomment-34837164

**Comment by itkach** [comment]
Zoom In/Zoom Out actions in Aard 2 work exactly the same as in Aard 1. They change text size, and WebView does reflow the text. Pinch-to-zoom is new in Aard 2 and is not present in Aard 1. Pinch zoom is a standard WebView function that changes the scale of the whole page, including images. Chromium-based WebView (Android 4.4 and newer) doesn't reflow text (there's a lot written about it, see for example https://code.google.com/p/android/issues/detail?id=62378). I can't change this. And I'm not sure I'd want to: note that horizontal scroll appears when there's wide content such as a table or large image or a long string without spaces (such as long url), text reflow alone can't help with that. Zooming out with pinch allows to see entire content, even if text gets way too small to be readable and then zoom back in to the content area of interest.

I'm not sure what sort of scaling behavior are you looking for.

**Comment by ildar** [comment]
You are completely right: to have a zoom that I wanted a user needs to tap
menu -> Zoom In/Out.
I confused Aard with some other app that did this "viewport change" (is
this the right name for it?) on two-finger-swipe-to-zoom.
No need to change anything.
Very sorry for the noise (again). Excuse me.
