### ISSUE TITLE
Use OmegaWiki dictionary data

### ISSUE THREAD

**Issue by probonopd** [itkach/aard2-android#24]
OmegaWiki is a collaborative project to produce a free, multilingual dictionary in every language, with lexicological, terminological and thesaurus information.

Not sure where this wish belongs, so I also posted it to https://github.com/itkach/slob/issues/2

**Comment by itkach** [comment]
> Not sure where this wish belongs

Forum at http://aarddict.org since this is not a an issue or software feature request.
