### ISSUE TITLE
Cортировка по времени

### ISSUE THREAD

**Issue by GiftedPowerfulWinner** [itkach/aard2-android#28]
Обратил внимание, что сортировка по времени (когда в правом верхнем углу пиктограмма ''Часы'') во вкладке история работает некорректно.
Независимо от выбора ''по убыванию'' или ''по возрастанию'' список выводится в каком-то случайном порядке, где сверху могут быть, например результаты за февраль-январь, в середине такие как ''два дня назад'', ''вчера'' , и так далее, совершенно вразнобой, логика никакая не прослеживается.
Предположил, что ''звёздочки'' избранных словарей могут как-то влиять на формирование списка, но даже когда все сняты - всё выглядит таким же образом.

С сортировкой по названию всё в порядке, и по убыванию и по возрастанию.

Но по дате как-то более удобно ориентироваться по недавно прочитанному, однако с вышеописанным это невозможно.
На форуме 4pda получил ответ, что такого бага у себя не видят.

**Comment by itkach** [comment]
> во вкладке история

а в закладках? код один и тот же

> На форуме 4pda получил ответ, что такого бага у себя не видят.

И я у себя такого не вижу. 

Попробуйте удалить историю (долгое нажатие, отметить всё, корзина) и посмотреть повторится ли проблема при наполнении новыми записями.

**Comment by GiftedPowerfulWinner** [comment]
Закладками до этого не пользовался, ничего не могу сказать по этому поводу. Историю удалил, сделал оперативно новую. Сейчас, пока интервалы между пунктами - минуты, всё показывается правильно. (Сделал из этих же пунктов закладки для теста - тоже ок). Пришлось правда перед всеми этими процедурами срезервировать сотни текстовиков из системного раздела (благо, устройство рутировано), а то как-то 'жалко' было бы историю, как напоминание о прочитанном, терять. Что само собой наводит на реквест о добавлении в программу какого-то более 'эргономичного' способа экспорта истории/закладок, чем такой 'костыль' с ручным копированием (потому что на каких-то девайсах с рутом могут быть проблемы, и резерв истории, если вдруг сабжевый баг повторится, не получить). Не знаю, может экспорт не добавлен как раз ввиду такой много-текстовиковой реализации хранения истории/закладок, но в перспективе, понятное дело, он бы не повредил.

**Comment by itkach** [comment]
> может экспорт не добавлен как раз ввиду такой много-текстовиковой реализации

Нет, просто руки не дошли. Кроме того, пока что никто не спрашивал :) 

> жалко' было бы историю

Историю честно говоря жалко не очень (по крайней мере лично мне :) ). Закладки - другое дело. Хотя вообщем и то и другое в текущей реализации не предназначены для долгосрочного хранения. И закладки, и история ограничены последними ста записями (по времени последнего доступа), это позволяет "отделаться" простой, но вполне полезной, реализацией загрузки/хранения/проверки. Возможно пересмотрим, если будет много пожеланий на эту тему.

**Comment by GiftedPowerfulWinner** [comment]
Кроме того, пока что никто не спрашивал :) 
Мыслю шире остальных значит, с опережением, прогрессивно)

Насчёт истории - ну, как я выше сказал, закладками не пользовался (ну не было таких прям мега-статей ''срочно_в_мемориз!''), так что моими закладками как раз была история)  

Касательно ограничений по хранению закладок/истории - лично моё мнение - не очень это хорошо для программы, которая, ну, в общем-то в образовательных целях используется. Не анекдоты же, где прочитал-забыл. Тут повторение-мать учения вполне актуальна, а то, вполне можно и начисто забыть, что там читалось пару месяцев назад, а если говорить о годах - то тем более. А так - оп, пробежал глазами списочек, оп, что за термин, подзабыл, ах да, помню-помню) Ну и так далее. 
Не знаю, лично у меня, даже на каких-то десктопных оболочках, которые, по понятным причинам используется реже, чем мобильные, история всегда 'ограничена' 9999 пунктов. Больше - вряд ли кому-то когда-либо понадобится, да и столько вряд ли когда-то наберётся, тем не менее это всё-таки не 'рамки' в виде 'жалкой' сотки пунктов. 
Понимаю ещё и то, что 10000 тысяч текстовиков во внутренней памяти андроид устройства - это как-то совсем не айс. То есть при текущей реализации хранения - анлимитед история невозможна и даже нежелательна. Вот писалось бы всё это в один текстовик (ну ладно - в два, закладки/заметки), тогда да ..)
Насчёт ''много пожеланий'' на эту тему - сомневаюсь , что таковых будет много (если будут вообще, не такой уж обширный процент пользователей мобильных операционок и вовсе дойдёт до мысли ''оффлайн википедия и Ко на устройстве'', а сколько из тех, что всё же пользуются, пишут какие-то фидбэки..) Ну и агитировать народ на тот же 4pda, ''ну надо ребят, надо, безлимитная история/экспорт закладок, вы чё, напишите разработчику!'' я наверное тоже не пойду)) 
Отдавая себе абсолютный отчёт , насколько на добровольных началах всё это делается, резюмирую реквест так ''ну, если не так сложна и времязатратна реализа-а-ация, то в перспективе ждём (жду) такого функционала в программе'')

На этом, с очередным мысленным респектом за такой софт, наверное заканчиваю (чего-то пост разросся), тем более, что сабжевый вопрос вроде решён (косяк кстати полюбому появился после обновления на какую-то версию. Абсолютно чистую переустановку делал лишь один раз, когда у приложения сменился сертификат, так что какой-то из последних апдейтов 'поверх' почему-то такую фигню наворотил. Может дело вовсе и не в программе, а фиг знает в чём, ну буду надеяться что при последующих апдейтах (в которых например будет экспорт истории ;-) подобное не повторится.

**Comment by ildar** [comment]
Извините, что вмешиваюсь.
Мне кажется, что для таких случаев человечество придумало резервное
копирование, для чего в случае рутованного андроида подходит, например,
oandbackup, а в случае отсутствия рута -
http://johan-notes.blogspot.com/2013/04/backuprestore-adb.html
