### ISSUE TITLE
Ccылки на смежные темы в конце статей

### ISSUE THREAD

**Issue by GiftedPowerfulWinner** [itkach/aard2-android#29]
Предыдущий дамп википедии не качал, но в свежем (20150319) такая же проблема, как и во всех последних lurkmore дампах - полное отсутствие в конце статей россыпи ссылок на смежные темы и разделы ( не внешние ресурсы, а находящиеся в самой вики)
Крайне удобная, и на мой взгляд, нужная фишка вики и википодобных библиотек таким образом теряется.

Это не реализуется ввиду какой-то технической невозможности, ограничений формата slob или ещё чего-то?
Возможно ли в будущем 'возвращение' этой полезной фичи в дампы?

**Comment by itkach** [comment]
> Крайне удобная, и на мой взгляд, нужная фишка 

У меня такого впечатления не сложилось:

> или ещё чего-то?

отношение к контенту статьи эти ссылки имеют весьма опосредованное, повторяются во многих местах, занимают кучу места визуально и в байтах. Посему отфильтрованы.

> Возможно ли в будущем 'возвращение' этой полезной фичи в дампы?

Желающие могут компилировать свои варианты с модифицированными фильтрами или вовсе без фильтров, [тулзы](https://github.com/itkach/mwscrape2slob) все доступны.
