### ISSUE TITLE
replace support-v13 jar file

### ISSUE THREAD

**Issue by ghost** [itkach/aard2-android#32]
Why is a jar file used when you manage your other dependencies via gradle? Shouldn't `compile "com.android.support:support-v13:18.0.0"` (or whatever version is required) do the same in a more sane way? See https://developer.android.com/tools/support-library/features.html#v13

**Comment by itkach** [comment]
The jar file was used because I had trouble locating specific required version of the support library in the repos (it wasn't 18.0.0) . This is resolved now (6a5f96341e32f43ea15d8b9ed774900ab15ab3e0, 5fdad9df354f999f751400d1fc15b0ed69f2f6a2)
