### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by GiftedPowerfulWinner** [itkach/aard2-android#33]
Android 4.2.2. После обновления на новую версию 0.25 при включённой тёмной теме интерфейса, в основном меню (под названиями вкладок) и вверху открытых статей появилась сплошная синяя полоса (то есть, маленькая полоса такого же цвета, подчёркивающая название активной вкладки была и есть, и под ней - ещё одна полоса такого же цвета, идущая через весь экран). Похоже на баг. При светлой теме этой полосы нет. Могу предположить, что как-то связано с нововведением Implemented fullscreen mode (Android 4.4+), но утверждать не берусь. Скриншот экрана сейчас не могу сделать, но если это обязательно нужно для наглядности (если на имеющемся устройстве подобное не проявляется),  и как-то поможет устранению - сделаю потом.

**Comment by itkach** [comment]
Если я правильно понимаю о чем идет речь, то эта полоска была там всегда, с момента включения тёмной темы, то есть с 0.17. Просто так выглядит action bar в тёмной Holo. Можно дискутировать на тему красиво/некрасиво, нужна она там или нет, но это не баг, а скорее вопросы к Гуглу. В принципе можно сделать свой вариант темы в приложении, но возни гораздо больше, чем беспокойства доставляемого (лично мне) это полоской.

**Comment by GiftedPowerfulWinner** [comment]
Хз тогда почему в глаза только сейчас бросилось. '' Ваш ответ понятен, господа знатоки'' (c). Не в тему, но спасибо за пересмотренную концепцию рандомного поиска  - так действительно лучше. Данный топик закрываю тогда.
