### ISSUE TITLE
article search view - dark background

### ISSUE THREAD

**Issue by cosmopol** [itkach/aard2-android#39]
Searching in the article view switches to a dark background although the style is set to 'light' and makes it hard to read the search text field on an e-ink ereader with open Android 4.2.

**Comment by itkach** [comment]
> makes it hard to read the search text field on an e-ink ereader with open Android 4.2.

`Find in page` uses OS implementation, I don't have control over it (short of completely re-implementing UI for it myself)

**Comment by itkach** [comment]
Find in page was re-implemented in [0.44](https://github.com/itkach/aard2-android/releases/tag/0.44)
