### ISSUE TITLE
global network switch

### ISSUE THREAD

**Issue by cosmopol** [itkach/aard2-android#41]
I herewith state that a secured dormant global network switch should be set as a default feature. Mr Tkach seems to be a very smart person and he surely will know what I mean by stating that.

**Comment by itkach** [comment]
Sorry to disappoint you. I have know idea what are you talking about.

**Comment by cosmopol** [comment]
It was just an idea. Maybe you will find it useful after thorough contemplation.

**Comment by itkach** [comment]
Even if it was an idea you didn't share anything to contemplate, thoroughly or otherwise. I think it's best to have this closed.
