### ISSUE TITLE
the philosophy behind Aard

### ISSUE THREAD

**Issue by cosmopol** [itkach/aard2-android#45]
- who is its author?
- what drives its author?
- where will it go?
- how will it evolve?

**Comment by cosmopol** [comment]
Could somebody please tell me where that project is supposed to be going? Maybe I would want to participate on a greater scale...

**Comment by itkach** [comment]
> where that project is supposed to be going

As far as I can tell it's more or less where it's supposed to be. But maybe nobody knows exactly. If you have ideas there's nothing preventing you from forking and implementing them.

http://aarddict.org/forum/ is probably a better place for vague philosophical discussions.
