### ISSUE TITLE
Open keyboard directly on search

### ISSUE THREAD

**Issue by francwalter** [itkach/aard2-android#48]
This is not a bug, only a very tiny feature quest:
When I press "find in page" the keyboard is not automatically opening. I have to press another time into the search field.
Would be more comfortable if it opened directly.
But this is maybe purpose and just I don't see the point. Then please close and forget, thank! 
:)
Frank

**Comment by itkach** [comment]
> When I press "find in page" the keyboard is not automatically opening

I noticed that too, but somehow it never bothered me enough to investigate :) 

"Find in page" uses [WebView's built-in implementation](http://developer.android.com/reference/android/webkit/WebView.html#showFindDialog(java.lang.String, boolean)) which takes parameter to show keyboard or not. I don't think I set it to false on purpose, it's probably just something that I overlooked. I'll change it.

As a side note, you may have noticed that [showFindDialog](http://developer.android.com/reference/android/webkit/WebView.html#showFindDialog(java.lang.String, boolean)) is marked deprecated with the following comment:

> This method does not work reliably on all Android versions; implementing a custom find dialog using WebView.findAllAsync() provides a more robust solution.

So Google can't make it work reliably on all Android versions, but somehow applications can, by implementing their own. I think this is nonsense. 

Interestingly, there was also an attempt in Mozilla to get rid of ability to invoke built-in find dialog with javascript - https://bugzilla.mozilla.org/show_bug.cgi?id=672395. 

Lets hope browser developers will come to their senses one day...

**Comment by itkach** [comment]
Fixed in e5a9aec2191e1b59183b3234c7ef6d2ab43f5295

**Comment by francwalter** [comment]
THANK!!!
Works on my S4 with CM12.1
