### ISSUE TITLE
CSS not recognized on Marshmallow?

### ISSUE THREAD

**Issue by Peters100** [itkach/aard2-android#56]
Android M.

Simple CSS:
img { display: none; }

Error:
"Doesn't appear to be a CSS file"

On Lolipop, there were no problems.

**Comment by itkach** [comment]
Works for me on Marshmallow. What's you CSS file name? Make sure it has
.css extension. The app simply looks at mime type as reported by OS to
check that selected file is at least a text file, not binary.

**Comment by Peters100** [comment]
I was able to identify the cause. The issue was with using the MIX file manager [ forum.xda-developers.com/showthread.php?t=1523691 ] to select the .css file. Using another fileman, the CSS was recognized correctly. Thanks.
