### ISSUE TITLE
Documentation: converting other formats to slob

### ISSUE THREAD

**Issue by marmistrz** [itkach/aard2-android#57]
I have a huge collection of stardict dictionaries. Unfortunately, there are no open source stardict apps for Android nowadays so I think about migrating to aard2. 

Is there any software to convert stardict to slob? Just give me a link and I'll put it into README myself and submit a pull request.

**Comment by itkach** [comment]
> Is there any software to convert stardict to slob?

Not that I am aware of. Quick search turns up a couple of Python libraries - [python-stardict](https://github.com/pysuxing/python-stardict) and [penelope]( https://pypi.python.org/pypi/penelope/) - that should be able to read startdict files. Shouldn't be too difficult for someone motivated to combine them with [slob.py](https://github.com/itkach/slob) to create a startdict -> slob converter. My impression, however, has always been that vast majority of startdict dictionaries were converted from some other sources, often in a lossy and incomplete fashion, including Wikipedia, freedict.org, XDXF dictionaries for which converters to slob are available (and many compiled dictionaries as well).

**Comment by ildar** [comment]
1. In fact, there is an Android Stardict app: https://f-droid.org/forums/topic/qdict-offline-dictionary-for-stardict-format/
2. But actually I already did the conversion Stardict -> slob:https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fjohan-notes.blogspot.com%2F2015%2F02%2Fblog-post.html&edit-text=&act=url (sorry, the original is in Russian)
3. The scipt to convert uses stardict-tools and  xdxf converter.
4. I coverted a pack of dictionaries, out em on GDrive but Igor didn't seem to be interested to add it to wiki.

**Comment by itkach** [comment]
> I coverted a pack of dictionaries, out em on GDrive but Igor didn't seem to be interested to add it to wiki.

I didn't know I was supposed to do that, and you don't need me to - any Github user can edit https://github.com/itkach/slob/wiki/Dictionaries and add links to dictionaries they made or host

> The scipt to convert uses stardict-tools and  xdxf converter.
Direct converter XDXF -> slob exists, no need to convert to aar first:  https://github.com/itkach/xdxf2slob
Also, note that a lot of dictionaries are available in XDXF format already: https://sourceforge.net/projects/xdxf/files/

**Comment by marmistrz** [comment]
On October 24, 2016 7:40:12 PM GMT+02:00, ildar <notifications@github.com> wrote:
>1. In fact, there is an Android Stardict
>app: https://f-droid.org/forums/topic/qdict-offline-dictionary-for-stardict-format/

Yes, I know about it, I'm its F-Droid maintainer and it depends on a binary blob libqdicteng.so for which sourcrs are not available (the binary was in fact removed from the repo). See the QDict issues.

>2. But actually I already did the conversion Stardict ->
>slob:https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fjohan-notes.blogspot.com%2F2015%2F02%2Fblog-post.html&edit-text=&act=url (sorry,
>the original is in Russian)

Great!

Please post the links in their original language :) It's easier than way for those who happen to know Russian :)

>3. The scipt to convert uses stardict-tools and  xdxf converter.
>4. I coverted a pack of dictionaries, out em on GDrive but Igor didn't
>seem to be interested to add it to wiki.

**Comment by ildar** [comment]
1. In fact, there is an Android Stardict app:
https://f-droid.org/forums/topic/qdict-offline-dictionary-for-stardict-format/
2. But actually I already did the conversion Stardict -> slob:
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fjohan-notes.blogspot.com%2F2015%2F02%2Fblog-post.html&edit-text=&act=url
(sorry, the original is in Russian)
3. The scipt to convert uses stardict-tools and  xdxf converter.
4. I coverted a pack of dictionaries, out em on GDrive but Igor didn't seem
to be interested to add it to wiki.
