### ISSUE TITLE
Configuration with name "default " not found

### ISSUE THREAD

**Issue by drisschobix** [itkach/aard2-android#60]
hello;
While i'm trying to import this project to android studio 1.1.0 ;so after creating gradles ,android studio show the folling error ;pls could you help me.

![capture](https://cloud.githubusercontent.com/assets/24933959/21785481/a5990fd6-d6b7-11e6-8533-8c37b45de153.JPG)

**Comment by itkach** [comment]
Current version of Android Studio appears to be 2.2.3. 1.1.0 is ancient. The source code is also not up to date. Use latest versions.
