### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by dalb8** [itkach/aard2-android#64]
Using the latest official apk, on stock LG G4 , Android 6 in Airplane mode , the following sometimes appears:

 ```Page Web non disponible

Impossible de charger la page Web http://127.0.0.1:8013/slob/7cdaa420-009f-4283-9ce3-b2803dd043e8/jeune?blob=7978-14# pour la raison suivante :

net::ERR_PROXY_CONNECTION_FAILED
```

If there is an internet available just a white screen.

**Comment by itkach** [comment]
are you running some kind of ad blocker that proxies network access?

**Comment by dalb8** [comment]
no

**Comment by itkach** [comment]
Well, something messed up network access. Perhaps there's a proxy configured - check advanced network settings. This works on thousands of devices, so there must be something special about yours.

**Comment by dalb8** [comment]
The app usually works fine. I don't have any proxies and as I said the problem exists even in airplane mode, though without any error message.

**Comment by itkach** [comment]
I can't reproduce this.
