### ISSUE TITLE
Error Project slobj.

### ISSUE THREAD

**Issue by trungdn0812** [itkach/aard2-android#67]
Error:Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :slobj.

**Comment by itkach** [comment]
Can you provide more details? Which version of gradle is used? Did you follow instructions at https://github.com/itkach/aard2-android#developing? Works here with gradle 3.0.

**Comment by trungdn0812** [comment]
Thanks, itkach. I had the answer
