### ISSUE TITLE
Other compression libraries support

### ISSUE THREAD

**Issue by data-man** [itkach/aard2-android#70]
For example, [zstd](https://github.com/facebook/zstd), [lz4](https://github.com/lz4/lz4) or [lizard](https://github.com/inikep/lizard).
They more faster than zip/lzma2/bzip2.

**Comment by MHBraun** [comment]
This is correct. 
We may either decide to maximise speed or to minimize data volume for the dictionaries. As I do not have any reports on slow behaviour of Aard2 with the largest wikipedias (enwiki and dewiki) on Android phones I rather stick with the maximum compression in generating the dictionaries.

**Comment by francwalter** [comment]
@MHBraun I agree completely.

**Comment by itkach** [comment]
Indeed, speed of compression/decompression vs compression ratio is a typical trade-off. Newer algorithms perhaps can approach or sometimes beat zlib's compression ratio while being faster, but none of them seem to reach compression ratios comparable to lzma (xz). lz4's extremely fast compression, while impressive and useful in many applications, is quite useless for read-only dictionary container where only fast decompression is important and high compression ratio is of value.

Another important consideration is availability of robust implementations that are compatible across versions, programming languages and platforms. zlib is ubiquitous and xz is nearly so (both are in Python standard library, for example, zlib's deflate is in Java standard library), and both are stable and mature. I don't think the same can be said about these new algorithms and libraries that implement them, so adopting them here would do more harm than good.
