### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by dimqua** [itkach/aard2-android#72]
Планируется ли применение material design в приложении?

**Comment by itkach** [comment]
Не планируется.  Есть 3rd party material design fork: https://play.google.com/store/apps/details?id=org.brainail.EverboxingLexis, посмотрите.

**Comment by staticssleever668** [comment]
Considering that the fork provided is closed source and not on F-Droid, may you review this issue again?
Material design is literally the standard in modern Android world

**Comment by itkach** [comment]
@staticssleever668 Nothing changed, I have no plans to work on Material design version. Regarding LexisPaper, it should come with source code being derivative of GPL3 software. It appears to be in violation of the license - I contacted the author, hopefully they can correct the problem.
