### ISSUE TITLE
Fails to find slob file on Samsung S5 Mini / Android 6.x

### ISSUE THREAD

**Issue by humenda** [itkach/aard2-android#76]
Hi,

on the mentioned model, Aard fails to find a dictionary below /storage/emulated. I am guessing that this path is not searched. If it is, there might be a privilege issue.

Furthermore, it would be great to have a button next to the usual dictionary search button, to choose a location manually. This way I could have circumvented the problem.

Thanks

**Comment by francwalter** [comment]
1. I wonder. Reading was never prohibited even in external sdcards.

2. I have this button! 
It's the + button the second of the up right corner when I am in the dictionary tab.
But I have no SGS5 mini.

**Comment by humenda** [comment]
This was my bad. Even though it's clearly visible that Aard is not Aard2, I installed the old one. I did expect Aard < 2 to be removed from the Playstore. With Aard2 it works.

Sorry for the noise :).
