### ISSUE TITLE
Cannoe view the content

### ISSUE THREAD

**Issue by tim-hub** [itkach/aard2-android#81]
- Android 7
- Samsung s6
- dict Wikitonary

No error reported, just close the app immediately when I click on the word.

**Comment by itkach** [comment]
First thing to check is integrity of the wiktionary file - make sure sha1 matches one from the download page.

**Comment by tim-hub** [comment]
Solve the problem, it is not from aard, it is from system, because Android 7 remove webview and use chrome as **webview**, I do not have android system webview after update the firmware from samsung. Fix it by force installing one.
