### ISSUE TITLE
Usability improvement: Access article search from article view

### ISSUE THREAD

**Issue by tomtom** [itkach/aard2-android#84]
I usually leave aard2 in the article view when I switch back to another app. When I want to lookup another term and switch to aard2 again, aard2 is still viewing article. I have to go back to the list in order to lookup the new term.

IMHO it would be preferable if I could enter a new search term from the article view. One could think of a search button in the toolbar that switches back to the list and opens the search box.

**Comment by itkach** [comment]
> IMHO it would be preferable if I could enter a new search term from the article view. One could think of a search button in the toolbar that switches back to the list and opens the search box.

The app already does that - tapping logo/title in article view takes you directly to lookup view even if you followed a few links.
