### ISSUE TITLE
Feature Request: Text Selection Menu Option

### ISSUE THREAD

**Issue by SiqingYu** [itkach/aard2-android#86]
When selection text in any app and web browser, the pop menu include a "Search Aard 2" option to quickly look up a word like the Wikipedia app does.
![screenshot_antennapod_20181012-115805](https://user-images.githubusercontent.com/22290018/46847287-1e6f1980-ce16-11e8-91dd-5dbb822a3021.png)

**Comment by MHBraun** [comment]
Nice idea. How did you add 'SEARCH WIKIPEDIA' to the list? I do not have it in my browser.

**Comment by SiqingYu** [comment]
@MHBraun Chrome has while Firefox doesn't. It depends on the app itself.

**Comment by doozan** [comment]
This should be a relatively easy feature to add, you just need to add an intent for ACTION_PROCESS_TEXT and then process that the same way the colordict.intent.action.SEARCH is handled.

https:// medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999
