### ISSUE TITLE
Strange problem: Cannot display content of any dictionary

### ISSUE THREAD

**Issue by alexagithuber** [itkach/aard2-android#87]
Hello
I have a strange problem on my NOTE4 phone running android 6.0.1 and aard2:
I can search dictionnaries, but don't see the content of any article. Tried to move the dicionary to Phone instead of SD card, load a new dictionary: no sucess. Uninstall/reinstall aard2 : no sucess.
This used to work on the exact same phone for years.
Could it be a android.permission.INTERNET permission issue?
Phone came back from samsung official repair and motehrboard change. No problem with any other program up to now.
Thanks for your help, as I use aard2 daily 100x!
Alex

**Comment by alexagithuber** [comment]
Hello,
a complement to the issue.
I noticed that when I turn the Wifi and I'm connected to the local Wifi network, it works, even if I turn off the "download external content" even in case of Wifi

I think the issue may be with my local web server on the phone, maybe unrelated to aard2, but no other applications shows any problem

Thanks for your help,

Alex

**Comment by alexagithuber** [comment]
Hello,
sorry I made a mistake...
the issue is not solved yet...
Alex

**Comment by itkach** [comment]
> I think the issue may be with my local web server on the phone, maybe unrelated to aard2, but no other applications shows any problem

Tell me more about your local web server. What does it do, how does it run? aard2, unlike most applications, does start an embedded web server that serves article content, on port 8013, so anything on the device that messes with networking - ad blockers, reverse proxies, firewalls, vpns - has a potential to interfere.

**Comment by alexagithuber** [comment]
Hello Igor,
thanks for answering. 
Actually I don't have any specific webserver, it's just my deduction that something is wrong with the webserver, since I read in the AARD2 manual that it uses a local webserver.
I can see the title of the article on the top in very small caracters but no content is displayed.
Also I noticed that when I'm connected to Wifi, it works fine, even if I turn off the "loading of the external contents" in AARD2.
I have a 2 year old Samsung Note 4, that broke down due to some known failing memory issue. It was sent to offical Samsung for warranty repair, they changed the motherboard, and reinstalled the system, so the phone is like brand new now. I have android 6.0.1 and there is no later update available for this phone.
Kernel version as displayed by the phone is 3.10.40-10100220.
MDF v2.0 Release 6
VPN v1.4 Release 6 (but i don't have any VPN )
ASKS v1.2 Relase 161011
SMR Aug 2017 Relase Q

I don't have VPN (but I used to have it installed, and AARD2 worked fine before), nor (known) proxies or firewalls.
Google Chrome and Firefox work fine. I don't have any added module in Firefox.
Aard2 used to work perfectly before that for 2 years (and before that AARD on a Note2). 
I also dont have any "fishy" or (known) special application (actually since the phone had a factory reset, I have less applications and none is new). AARD2 was one of the first I reinstalled, and it didn't work immediately

How can I check the good working ot the embedded webserver ? Or can I restart it?

I did a backup restore using Samsung Smart Switch (I don't know if that has half installed some application?). But i used that already on my transfer from Note 2 to Note 4 without a problem.
BTW Aard2 works fine on my old Note2.

BTW: I have my dictionaries on the SD card that I moved from Note 4 to Note 2 during repair, and back to Note 4 after repair. I tried to load some small new dictionary, but with the same problem, so it seems not to be the problem ?

Thanks for your help and let me know how I can help identify the problem

AARD2 is certainly the application I used the more on my phone!

Alex

**Comment by tuetschek** [comment]
Hi,

I'm having exactly the same issue on my LG G Flex 2 with Android 6.0. Everything works as long as my phone is connected to WiFi. Nothing works over 4G (articles never load) or with data disabled (I get a net::ERR_PROXY_CONNECTION_FAILED error). I don't use any VPN, or a proxy as far as I know. I do have uBlock within Firefox, but that shouldn't have any influence outside, I hope. Any idea what I could try? Aard2 is really great and I'd love to be able to use it always. 

Thanks,
Ondrej

**Comment by tuetschek** [comment]
@itkach : you're right – thanks for your help! The app worked without the SIM, so I checked my mobile data configuration and it turned out there was a proxy configured by default. I'm guessing my phone somehow confused MMS & data settings pushed by the operator (giffgaff – UK), since the configuration instructions on my operator's website do not specify any proxy for data, just for MMS, and my phone seems to have used the same proxy for both. I entered manually the recommended configuration from the operator's website and now everything seems to work fine :-).

**Comment by alexagithuber** [comment]
Hello Igor an Ondrej
it's exactly that. I followed your instructions. When I removed the SIM card everything works fine.
I tried to setup myself the APN (Swisscom), following this page:
https://devicesupport.swisscom.ch/samsung/galaxy-note9/getting-started/set-up-your-mobile-phone-for-internet
but it didn't work.
So at the end I took the lazy solution and asked the operator to send me a Configuration message. I saw in the APN setting that it removed the PROXY settings (which were supposed to be  192.168.210.1). And Now it works ! 

For my curiosity, what is the function of the proxy in setting up an APN for the phone to connect to the Internet?

Thanks again Igor for your nice application, and Ondrej for helping to  point to a solution.

Best regards,

Alex

**Comment by itkach** [comment]
> For my curiosity, what is the function of the proxy in setting up an APN for the phone to connect to the Internet?

My understanding is that it's one of the ways to secure the network, by blocking all the traffic and explicitly allowing HTTP access via dedicated proxy servers. My impression is that this approach is rarely used these days as the same can be implemented in provider's infrastructure and be transparent to users instead of requiring all client applications to be correctly configured to use a proxy server.
