### ISSUE TITLE
Add dialog to install FreeDict dictionaries

### ISSUE THREAD

**Issue by humenda** [itkach/aard2-android#88]
FreeDict ships over 145 dictionaries in the slob format and we consequently recommend on our website to install Aard2 on Android to make use of it. For convenience
reasons, it would be great to offer the user the possibility to let the program itself fetch the requested dictionaries. This could be an option in the  side menu, opening a simple Android view presenting all FreeDict dictionaries to the user.

This is going to be quick to implement, especially because FreeDict offers an API for this; see https://github.com/freedict/fd-dictionaries/wiki/FreeDict-API

Is there interest to integrate this into Aard2?

**Comment by itkach** [comment]
> FreeDict ships over 145 dictionaries in the slob format and we consequently recommend on our website to install Aard2 on Android to make use of it.

I wasn't aware of this. Awesome!

https://freedict.org/downloads/

> For convenience
> reasons, it would be great to offer the user the possibility to let the program itself fetch the requested dictionaries.

> recommend on our website to install Aard2 on Android

I noticed you mention F-Droid, but Aard 2 is actually not available there (not sure what's preventing F-Droid folks from including it, but the fact remains that it is not there). Perhaps APK download from https://github.com/itkach/aard2-android/releases is a better recommendation

>  For convenience reasons, it would be great to offer the user the possibility to let the program itself fetch the requested dictionaries.

This comes up every once in a while, for example most recently  here: https://github.com/itkach/aard2-android/releases. 

I agree that a dictionary manager that can download and update dictionaries may be a nice thing to have and will somewhat reduce setup friction for most users - if well implemented. Those who propose this, though, vastly underestimate the effort as well as the impact on managing user-compiled dictionary contributions. I remain of the opinion that download convenience a built-in dictionary management may bring over the current low-tech approach of downloading files via links from collaboratively maintained wiki page is not worth the complexity.
