### ISSUE TITLE
instant translate

### ISSUE THREAD

**Issue by bam80** [itkach/aard2-android#91]
Google Translate has a cool feature - Tap to Translate.
It allows to translate selected text from any app.
Can it be implemented here?

**Comment by itkach** [comment]
Selected text can already be translated from any app via "Share" and by the looks of it it's the same number of taps as with Google Translate's Tap to Translate. With Translate, user selects text, taps "Copy", then taps briefly appearing Google Translate button. Using "Share", user selects text, taps "Share" then taps "Aard 2" in "Share via" app icon grid. Back button in "Aard 2" closes it and takes user back to the app from which word lookup was performed. Tap to Translate doesn't seem to be much of an improvement.
