### ISSUE TITLE
Cosmetic issue (clipped icons) with release 0.41

### ISSUE THREAD

**Issue by jcp-sd** [itkach/aard2-android#93]
I noticed that many of the icons in UI became clipped / truncated right after upgrading to release 0.41 (installed and upgraded through the Play Store). I have used Aard2 for quite awhile and just recently before upgrading from 0.40 to 0.41 and never noticed this before.

Eveything else seems to function just fine for me in release 0.41

Great app, and searches are fast for such a small, brain damaged device!

Device: Moto-G4 phone
OS: Android 7.0 (April 1, 2018 security patches)
Display: 1920 x 1080

![Screenshot_20190617-150818](https://user-images.githubusercontent.com/16908384/59640752-ed1cbb00-9113-11e9-926b-41d0136c91fc.png)

**Comment by itkach** [comment]
I had to upgrade Android support dependencies and switch to a different icon font library that works with Android's current resource compiler. Didn't see any clipping issues on my devices. Will need to investigate, thanks for the report.

**Comment by MHBraun** [comment]
Can not confirm the icon cutting on

LG V20 H990DS with Android 8.0.0

**Comment by jcp-sd** [comment]
It does not seem to be an issue, problem on other devices.

I have the latest release of Aard2 insalled on a tablet device, and _no problems_ there.

No worries, sounds like it could be tricky to isolate the problem.

**Comment by CaptainFrosty** [comment]
I also have this issue, on an Samsung SM-G55U running stock Nougat

**Comment by itkach** [comment]
@jcp-sd @CaptainFrosty try https://github.com/itkach/aard2-android/releases/tag/0.43, [looks like this was fixed in the font icon library](https://github.com/kazy1991/FontDrawable/issues/6), but I was using an older version...

**Comment by jcp-sd** [comment]
I just upgraded to release 0.43 (the f-droid build) and everything looks OK with the icon issue.

Thank you itkach !

**Comment by CaptainFrosty** [comment]
this is fixed and can be closed
