### ISSUE TITLE
Transparent GoldenDict/ColorDict replacement (compatible action API?)

### ISSUE THREAD

**Issue by eugene-bright** [itkach/aard2-android#96]
Some time ago there was a good app GoldenDict (RIP). It was designed as a replacement for ColorDict, another good dictionary manager app.

Other market apps were tightly integrated with the ColorDict at the moment of GoldenDict release. So the later one choose to mimic ColorDict's API to replace it seamlessly.

Is it possible to make Aard to implement [this API][colordict_api] to replace GoldenDict in the same way?

[colordict_api]: http://blog.socialnmobile.com/2011/01/colordict-api-for-3rd-party-developers.html "ColorDict action API"

**Comment by eugene-bright** [comment]
[Related google groups thread](https://groups.google.com/forum/#!msg/aarddict/uNy1EqoMoVI/o6Yw-_9IBgAJ)

**Comment by itkach** [comment]
[It already implements ColorDict's search intent.](https://github.com/itkach/aard2-android/commit/563715227e8f5934c299c1761f16d769552dc31a) Looks like the rest of the API relates to dictionary pop-up properties and are irrelevant for aard2 since it doesn't implement pop-up mode (and no plans to).
